services:
  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:?error}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - ${PGADMIN_PORT:-8080}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - backend
    volumes:
      - pgadmin-local-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres-local-data:
    driver: local
  pgadmin-local-data:
    driver: local

networks:
  backend:
    driver: bridge
